# Change these first
owner: bidscript           # Your GitHub organization or username, where this repository lives
repo: uptime       # The name of this repository

sites:
  - name: Tender Automation Platform
    url: https://app.bidscript.co.uk/app

status-website:
  baseUrl: /uptime
  name: Bidscript Status
